apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  labels:
    app: timescaledb
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
  selector:
    app: timescaledb
  type: ClusterIP
