# pgdata-pv-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescale-pgdata-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
